
Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mcredential-initializer[0m
{"level":"info","ts":1598342856.3208141,"caller":"creds-init/main.go:44","msg":"Credentials initialized."}

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mworking-dir-initializer[0m

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mplace-tools[0m

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-dryice-devops-python-flask-dock-xh6s4-xqrvt[0m
{"level":"info","ts":1598342863.371466,"caller":"git/git.go:105","msg":"Successfully cloned https://github.com/*************/python-flask-docker.git @ v0.0.3 in path /workspace/source"}
{"level":"warn","ts":1598342863.3718603,"caller":"git/git.go:152","msg":"Unexpected error: creating symlink: symlink /tekton/home/.ssh /root/.ssh: file exists"}
{"level":"info","ts":1598342863.4287179,"caller":"git/git.go:133","msg":"Successfully initialized and updated submodules in path /workspace/source"}

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mdryice-devops-python-flask-dock-xh6s4-3[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0825 08:07:46.552672      10 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0825 08:07:46.565861      10 metadata.go:248] Failed to unmarshal scopes: json: cannot unmarshal string into Go value of type []string
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker.io/learningjenkinsx/python-flask-docker:0.0.3": creating push check transport for index.docker.io failed: GET https://auth.docker.io/token?scope=repository%3Alearningjenkinsx%2Fpython-flask-docker%3Apush%2Cpull&service=registry.docker.io: unsupported status code 401
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.[0m
